### ISSUE TITLE
Missing table error when using `swga count --input ...`

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#20]
Trying to specify a primer set to count using `swga count --input` yields this error:

Traceback (most recent call last):
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/bin/swga", line 9, in <module>
    load_entry_point('swga==0.3.1', 'console_scripts', 'swga')()
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/swga_entry.py", line 47, in main
    command_opts[args.command](remaining, args.config)
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/count.py", line 20, in main
    count_specific_kmers(kmers, cmd.fg_genome_fp, cmd.bg_genome_fp)
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/count.py", line 27, in count_specific_kmers
    existing = [p.seq for p in Primer.select().where(Primer.seq << kmers)]
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/peewee.py", line 2558, in __iter__
    return iter(self.execute())
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/peewee.py", line 2551, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/peewee.py", line 2243, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/peewee.py", line 2877, in execute_sql
    self.commit()
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/peewee.py", line 2732, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/peewee.py", line 2869, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: primer

**Comment by sesh-sas** [comment]
This appears to work now?
