### ISSUE TITLE
Primer locations not stored as integers

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#24]
When trying to export bedfiles for a primer set, this error occurs:

    swga export bedfile --limit 1 --order_by score
    ...
    Exporting set 49575 and associated primers as bedfiles...
    Traceback (most recent call last):
      File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/bin/swga", line 9, in <module>
        load_entry_point('swga==0.3.2', 'console_scripts', 'swga')()
      File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/swga_entry.py", line 47, in main
        command_opts[args.command](remaining, args.config)
      File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/export.py", line 61, in main
        export_bedfiles(set, cmd.fg_genome_fp, outpath)
      File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/export.py", line 172, in export_bedfiles
        for location in primer.locations[record]:
    TypeError: string indices must be integers

**Comment by eclarke** [comment]
Noted, in the meantime, try using the set ID for bedfile output instead of sort/limit.





On Sun, May 17, 2015 at 11:52 AM -0700, "sesh-sas" <notifications@github.com> wrote:












When trying to export bedfiles for a primer set, this error occurs:

swga export bedfile --limit 1 --order_by score
...
Exporting set 49575 and associated primers as bedfiles...
Traceback (most recent call last):
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/bin/swga", line 9, in <module>
    load_entry_point('swga==0.3.2', 'console_scripts', 'swga')()
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/swga_entry.py", line 47, in main
    command_opts[args.command](remaining, args.config)
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/export.py", line 61, in main
    export_bedfiles(set, cmd.fg_genome_fp, outpath)
  File "/media/8TB_PLAYGROUND/home/sesh/SWGAScriptTesting/swga_workspace/local/lib/python2.7/site-packages/swga/commands/export.py", line 172, in export_bedfiles
    for location in primer.locations[record]:
TypeError: string indices must be integers

**Comment by sesh-sas** [comment]
Same error using
    swga export bedfile --ids 49575

**Comment by eclarke** [comment]
Does it happen with all sets or just that one?

Sent from my phone




On Sun, May 17, 2015 at 11:55 AM -0700, "sesh-sas" <notifications@github.com> wrote:












Same error using

    swga export bedfile --ids 49575

**Comment by sesh-sas** [comment]
All of them for this run. I haven't tested other runs

**Comment by eclarke** [comment]
fixed in b750f9831f6f22299a6515fd4a0b36817768287c
