### ISSUE TITLE
Need a better error message for trying to score a set whose primers are not in the database or are not active

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#28]
Running SWGA score for a set of primers that have not been added to or activated in the database produces a useless error.

Can we make what the user did wrong clearer?
```
swga score --input Set.txt

Traceback (most recent call last):
 File "/home/eloy/swga_workspace/bin/swga", line 9, in <module>
   load_entry_point('swga==0.3.4', 'console_scripts', 'swga')()
 File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/commands/swga_entry.py", line 47, in main
   command_opts[args.command](remaining, args.config)
 File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/commands/score.py", line 41, in main
   interactive=True)
 File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/commands/score.py", line 56, in score_set
   binding_locations = swga.locate.linearize_binding_sites(primers, chr_ends)
 File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/locate.py", line 36, in linearize_binding_sites
   for rec, locs in json.loads(primer.locations).iteritems():
 File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
   return _default_decoder.decode(s)
 File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by eclarke** [comment]
This should be fixed in the most recent versions of SWGA.
