### ISSUE TITLE
swga count fails if no exclude file is present

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#29]
Running `swga count` with exclude fp = None (generated by `swga init`) results in this error

Binary kmer file already exists at .swga_tmp/Plasmodium_vivax.ASM241v1.27.dna.toplevel.fasta-5mers.solid_kmers_binary; parsing...
Binary kmer file already exists at .swga_tmp/humangenome.fasta-5mers.solid_kmers_binary; parsing...
Traceback (most recent call last):
  File "/home/eloy/swga_workspace/bin/swga", line 9, in <module>
    load_entry_point('swga==0.3.6', 'console_scripts', 'swga')()
  File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/commands/swga_entry.py", line 61, in main
    command_opts[args.command](remaining, args.config)
  File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/commands/count.py", line 24, in main
    count_kmers(**cmd.args)
  File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/commands/count.py", line 104, in count_kmers
    assert os.path.isfile(exclude_fp)
AssertionError

**Comment by eclarke** [comment]
Fixed in commit 69d8b949a07e52c206af86dfb01b64742d6cd684
