### ISSUE TITLE
Problem scoring old sets

### ISSUE THREAD

**Issue by sesh-sas** [eclarke/swga#31]
Sets appear not to be reading in and/or activating correctly.

The command "swga count --input oldsets.txt" appears to recognize that the primers have already been found in a previous swga run:
```
(swga_workspace)[eloy@hem-shwhn-050-med-upenn-edu 101415oldsets]$ swga count --input Sesholdprimers.txt 
Command: count
- fg_genome_fp: /home/eloy/swga_workspace/swga-master/SWGA_Pvivax/101215-testingoldsets/Pvivax.fasta
- exclude_fp: /home/eloy/swga_workspace/swga-master/SWGA_Pvivax/101215-testingoldsets/SalIMitochondrialsequence.fasta
- max_dimer_bp: 3
- bg_genome_fp: /home/eloy/swga_workspace/swga-master/SWGA_Pvivax/101215-testingoldsets/humangenome.fasta
- min_fg_bind: 226
- min_size: 5
- input: <open file 'Sesholdprimers.txt', mode 'r' at 0x18fbc90>
- exclude_threshold: 1
- max_bg_bind: 21037
- max_size: 12
- primer_db: primers.db
AACGAAAAAA already exists in db, skipping...
ACGAAACG already exists in db, skipping...
CCGTTCG already exists in db, skipping...
CGAAAAAAAA already exists in db, skipping...
CGAAACGG already exists in db, skipping...
CGAACGAA already exists in db, skipping...
CGCAACG already exists in db, skipping...
CGCACGA already exists in db, skipping...
CGTTGCG already exists in db, skipping...
CGTTTCGC already exists in db, skipping...
CGTTTCGT already exists in db, skipping...
CGTTTTCG already exists in db, skipping...
CGTTTTTTTT already exists in db, skipping...
GCGAAAAAA already exists in db, skipping...
GCGAAATG already exists in db, skipping...
TCGTGCG already exists in db, skipping...
TTTTTTCGC already exists in db, skipping...
TTTTTTTCGT already exists in db, skipping...
Binary kmer file already exists at .swga_tmp/Pvivax.fasta-8mers.solid_kmers_binary; parsing...
Binary kmer file already exists at .swga_tmp/humangenome.fasta-8mers.solid_kmers_binary; parsing...
Writing 0 8-mers into db in blocks of 199...
Binary kmer file already exists at .swga_tmp/Pvivax.fasta-15mers.solid_kmers_binary; parsing...
Binary kmer file already exists at .swga_tmp/humangenome.fasta-15mers.solid_kmers_binary; parsing...
TCGTTCGTCGGCGAA does not exist in foreground genome, skipping...
Writing 0 15-mers into db in blocks of 199...
```
--------------------------------
But when I try to activate them it says they are not in the database (see below) and attepts to score them do not work.
-------------------------------
```
(swga_workspace)[eloy@hem-shwhn-050-med-upenn-edu 101415oldsets]$ swga activate --input Sesholdprimers.txt 
Command: activate
- reset: False
- input: <open file 'Sesholdprimers.txt', mode 'r' at 0x1928d20>
- bg_genome_fp: /home/eloy/swga_workspace/swga-master/SWGA_Pvivax/101215-testingoldsets/humangenome.fasta
- fg_genome_fp: /home/eloy/swga_workspace/swga-master/SWGA_Pvivax/101215-testingoldsets/Pvivax.fasta
- primer_db: primers.db
TCGTTCGTCGGCGAA not in the database; skipping. Add it manually with `swga count --input <file>` 
AACGAACG not in the database; skipping. Add it manually with `swga count --input <file>` 
Traceback (most recent call last):
  File "/home/eloy/swga_workspace/bin/swga", line 9, in <module>
    load_entry_point('swga==0.3.6', 'console_scripts', 'swga')()
  File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/commands/swga_entry.py", line 61, in main
    command_opts[args.command](remaining, args.config)
  File "/home/eloy/swga_workspace/lib/python2.7/site-packages/swga/commands/activate.py", line 17, in main
    swga.database.Primer.update_Tms(primers)
AttributeError: type object 'Primer' has no attribute 'update_Tms'
```

**Comment by eclarke** [comment]
Hey, there was a change in the database format between versions of swga. You can fix this by making a new workspace and installing a new copy of swga. Real sorry about that, didn't check to see if it'd break when people upgraded. 

Same issue as #30.

**Comment by eclarke** [comment]
Oops! I was wrong, this was actually a bug in `swga activate`. If you don't mind, please update and try again, and let me know if there are still problems...
