### ISSUE TITLE
Unknown error swga

### ISSUE THREAD

**Issue by icclark** [eclarke/swga#38]
Hi, 

I'm having trouble running the program. Installation appears to be successful, but I get the following error when I run the command swga. The program downloads python2.6 into swga_workspace, but claims to need >2.7. Could this be the issue? 

Thanks for any help you can give. 

Cheers, Iain 

swga
Traceback (most recent call last):
  File "/global/home/users/icclark/swga_workspace/bin/swga", line 9, in <module>
    load_entry_point('swga==0.4.3', 'console_scripts', 'swga')()
  File "/global/home/users/icclark/swga_workspace/lib/python2.6/site-packages/pkg_resources.py", line 468, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/global/home/users/icclark/swga_workspace/lib/python2.6/site-packages/pkg_resources.py", line 2563, in load_entry_point
    return ep.load()
  File "/global/home/users/icclark/swga_workspace/lib/python2.6/site-packages/pkg_resources.py", line 2254, in load
    ['__name__'])
  File "/global/home/users/icclark/swga_workspace/lib/python2.6/site-packages/swga/main.py", line 9, in <module>
    import workspace
  File "/global/home/users/icclark/swga_workspace/lib/python2.6/site-packages/swga/workspace.py", line 34
    m = {key: getattr(m, key) for key in m.fieldnames() if key != 'id'}
                                ^
SyntaxError: invalid syntax

**Comment by eclarke** [comment]
Hi Iain,

It does seem like the error is in the 2.7 vs 2.6 python. I don't think the install process does anything besides copy the system python, which in your case may be 2.6. I would suggest trying to update the version of python that you use to call `python virtualenv.py ~/swga_workspace` in the installation instructions. Even just downloading and installing it locally, then calling it via `~/path/to/python2.7 virtualenv.py ~/swga_workspace` would probably work.

Please let me know if that works.

Cheers,
Erik

**Comment by druvus** [comment]
I would recommend you to look into conda to handle your python installation. SWGA is added to bioconda so you may install by following instructions here: https://bioconda.github.io/recipes/swga/README.html

**Comment by icclark** [comment]
Hi guys, thanks very much for the replies! I installed via bioconda and
everything appears to be working. Cheers, Iain

**Comment by eclarke** [comment]
Hi Iain, glad it's working, but I'd suggest you use the GitHub version for now. The bioconda version is a bit out of date and the current version has a number of important bugfixes (Thank you @druvus for putting it on bioconda- I just need to update the recipe!)

Conda can be used to install an up-to-date version of Python (which it sounds like you already have done now), so I'd recommend using the traditional installation method for the time being, but using Conda's version of Python. I'll ping you when the bioconda recipe is updated.

**Comment by druvus** [comment]
I updated swga in Bioconda to the latest commit so it should now be ok to use.

**Comment by icclark** [comment]
Thanks Andreas!

**Comment by icclark** [comment]
Hey Erik,

I have a quick question, sorry to bother you. I'm trying to design
primers to amplify up HIV (~10kb) that is integrated in the human
genome. I wanted to capture HIV sequence diversity, so I did a
multiple sequence alignment and only used regions of HIV that were
conserved 90% of the time. This gave me a consensus sequence with a
bunch of N's, which I parsed into a fasta with each entry containing
sequences > 8bp with no N's. I then used this as my bg genome to run
swga. The best set so far contains primers that clearly overlap
(TTTCGGGTTTAT, TTTTCGGGTTTA), which suggests that my approach is
somehow messing up selection. Do you have any thoughts on what I might
be doing wrong. By splitting the genome into small pieces, I've lost
information about the distance of the pieces from each other, and swga
won't have any idea how to reasonably space the primers.  Would it be
better to use a bg genome with gaps ('-') or N's? Can swga handle that
type of input correctly?

Thanks for your thoughts,
Iain


  PRIMER SUMMARY

  ---------------

  There are 2778 primers in the database.


  200 are marked as active (i.e., they passed filter steps and will be

  used to find sets of compatible primers.)


  The average number of foreground genome binding sites is 1.

      (avg binding / genome_length = 0.000305)

  The average number of background genome binding sites is 5575.

      (avg binding / genome_length = 0.000002)


  The melting temp of the primers ranges between 45.91C and 59.78C
with an average of 53.90C.



  SETS SUMMARY

  ---------------

  There are 55590 sets in the database.

  The best scoring set is #5, with 6 primers and a score of 0.000000.

  Various statistics:

   - set_size........:          6

   - bg_dist_mean....: 9.88964E+06

   - fg_max_dist.....:         28

   - fg_dist_mean....:     5.4125

   - fg_dist_std.....:    5.34293

   - fg_dist_gini....:   0.503247

   - scoring_fn......: (fg_dist_mean * fg_dist_gini) / (bg_dist_mean)

  The primers in Set 5 are:

  AAATTTTCGGGT, CAAAATTTTCGG, CACTATGGGCG, CCGCTAGTCAAA, TTTCGGGTTTAT,
TTTTCGGGTTTA

**Comment by eclarke** [comment]
For the questions regarding overlaps, let's move the discussion to #39. 

Regarding the use of small foregrounds, you're not the only person using swga for smaller viral sequences. I haven't tested it for inputs like those, but I don't think the default parameters will be suitable. swga interprets each fasta record in the fg as a chromosome and understands that distances don't span record breaks. In your case, that may not be biologically accurate.

It may actually be better to just include a selection of representative HIV genomes as the foreground genome, one per record, and try it that way. Again, though, I haven't tested it in that case and can't say for certain that it would work as expected.

**Comment by saclarkPHE** [comment]
Hi,

I'm also having problems running the programme. After a seemingly successful installation, I run the swga command and get:

Traceback (most recent call last):
  File "/home/ste/miniconda2/bin/swga", line 4, in <module>
    import swga.main
  File "/home/ste/miniconda2/lib/python2.7/site-packages/swga/main.py", line 9, in <module>
    import workspace
  File "/home/ste/miniconda2/lib/python2.7/site-packages/swga/workspace.py", line 161, in <module>
    class Set(SwgaModel):
  File "/home/ste/miniconda2/lib/python2.7/site-packages/swga/workspace.py", line 170, in Set
    primers = ManyToManyField(Primer, related_name='sets')
TypeError: __init__() got an unexpected keyword argument 'related_name'

Ive tried the method outlined in the installation instructions (within Virtualenv) and using miniconda but with the same TypeError in __init__. I'm running Python 2.7.14 and GCC 5.4.0.

Any help would be appreciated. I'm a complete Linux/command line noob so the more idiot proof the better.

Many thanks!

**Comment by eclarke** [comment]
Hi @saclarkPHE, I've moved your comment into a new issue so I can keep track. Please reference issue #41
